### PR TITLE
Enable setting Δt in minimal_period

### PR DESCRIPTION
**Pull request by JonasKoziorek**
Enables user to select keyword argumet `Δt`, eg. time step between points in `po.points` trajectory. This refers to comment in #22. If the keyword is not specified, `Δt` is set to default `T/100`. This keyword argument is only valid for continuous-time systems.

### CODE REVIEW

**Review by Datseris — CHANGES_REQUESTED** [review]
That was not really my comment. My comment was that `minimal_period` should not care about `Dt`. It should re-use the same points of the PO it took as input. The points on the PO remain the same if you have 5 times the period or 1. So my suggestion is that `minimal_period` should never call `complete_orbit`. Rather it should just remake the same periodic orbit with the same `po.points` and just the reduced period.

**Comment by JonasKoziorek** [comment]
> The points on the PO remain the same if you have 5 times the period or 1.

The geometric curve in the state space remains (in theory) the same. In practice if we compute 50*minimal_T trajectory and the PO is unstable, the ODE solver will diverge from the correct trajectory. Furthermore, N*minimal_T might have duplicate points compared to minimal_T.

**Comment by Datseris** [comment]
Okay. So, if I understand correctly, **we, the codebase** never call `minimal_period`. This is aconvenience function we offer to the user. Hence, it is fine if the orbit is re-completed. Correct?

**Comment by JonasKoziorek** [comment]
We don't call `minimal_period` by default anywhere. For now it is a convenience function for the user. In the future I think there might be a situation where `minimal_period` is called inside of a detection algorithm.

**Review by Datseris — APPROVED** [review]

**Pull request merged**
