### PR TITLE
Porting Schmelcher-Diakonos

### PR DESCRIPTION
**Pull request by JonasKoziorek**
EDIT: Porting Schmelcher-Diakonos algorithm that is currently in [ChaosTools.jl](https://juliadynamics.github.io/DynamicalSystemsDocs.jl/chaostools/stable/periodicity/#ChaosTools.periodicorbits) into this repository. This PR contains algorithm, docs and tests.

### CODE REVIEW

**Comment by Datseris** [comment]
> Documentation will be added in the next PR.

Why? Why not in this PR?

**Comment by Datseris** [comment]
the docstring is already 90% of the documentation and that is here.

**Comment by JonasKoziorek** [comment]
I added the docs.

**Comment by Datseris** [comment]
I need to first look at the main interface and then I will review here.

**Review by Datseris — APPROVED** [review]

**Comment by Datseris** [comment]
I am approving this as it is for me easier to give a fresh review of the whole codebase later by opening an issue (unfortunately I am too busy now as the term started and i have to prepare courses)

**Pull request merged**
